2025-01-26 19:30:45,912 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\projects_for_university\Lessons\project1\Module12\module_12_4\tests_12_4.py", line 70, in test_run
    runner_2 = rt_with_exceptions.Runner(12,10)
  File "D:\projects_for_university\Lessons\project1\Module12\module_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-26 19:30:45,914 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\projects_for_university\Lessons\project1\Module12\module_12_4\tests_12_4.py", line 46, in test_walk
    runner_1 = rt_with_exceptions.Runner('Ni12ck', -2)
  File "D:\projects_for_university\Lessons\project1\Module12\module_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
